/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2025-03-05 03:04:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Signup Module</title>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      background-color: #f8f9fa;\r\n");
      out.write("    }\r\n");
      out.write("    header {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      background-color: #a3d9c9;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("      padding: 10px 20px;\r\n");
      out.write("      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo {\r\n");
      out.write("      height: 50px;\r\n");
      out.write("    }\r\n");
      out.write("    .container {\r\n");
      out.write("      max-width: 500px;\r\n");
      out.write("      margin: 50px auto;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      background: #fff;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("    .form-control {\r\n");
      out.write("      margin-bottom: 15px;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <header class=\"navbar navbar-expand-lg navbar-light bg-light px-3\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("      <img src=\"https://x-workz.in/static/media/Logo.cf195593dc1b3f921369.png\" alt=\"Logo\" class=\"logo\">\r\n");
      out.write("    </a>\r\n");
      out.write("    <div class=\"ms-auto\">\r\n");
      out.write("      <a href=\"index\" class=\"btn btn-primary me-2\">HOME</a>\r\n");
      out.write("      <a href=\"signiIn.jsp\" class=\"btn btn-outline-primary\">Sign In</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <h2 class=\"text-center mb-4\">Signup</h2>\r\n");
      out.write("    <form action=\"signup\" method=\"post\">\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <span class=\"input-group-text\"><i class=\"fas fa-user\"></i></span>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"name\" placeholder=\"Enter your username\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <span class=\"input-group-text\"><i class=\"fas fa-id-badge\"></i></span>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"loginID\" placeholder=\"Enter your login ID\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <span class=\"input-group-text\"><i class=\"fas fa-envelope\"></i></span>\r\n");
      out.write("        <input type=\"email\" class=\"form-control\" name=\"email\" placeholder=\"Enter your email\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <span class=\"input-group-text\"><i class=\"fas fa-phone\"></i></span>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"phoneNo\" placeholder=\"Enter your phone number\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <span class=\"input-group-text\"><i class=\"fas fa-lock\"></i></span>\r\n");
      out.write("        <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"Enter your password\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <span class=\"input-group-text\"><i class=\"fas fa-lock\"></i></span>\r\n");
      out.write("        <input type=\"password\" class=\"form-control\" name=\"confirmPassword\" placeholder=\"Confirm your password\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <span class=\"input-group-text\"><i class=\"fas fa-map-marker-alt\"></i></span>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"location\" placeholder=\"Enter your location\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"mb-3\">\r\n");
      out.write("        <label class=\"form-label\">Gender:</label>\r\n");
      out.write("        <div class=\"form-check form-check-inline\">\r\n");
      out.write("          <input class=\"form-check-input\" type=\"radio\" name=\"gender\" value=\"male\" required>\r\n");
      out.write("          <label class=\"form-check-label\">Male</label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-check form-check-inline\">\r\n");
      out.write("          <input class=\"form-check-input\" type=\"radio\" name=\"gender\" value=\"female\" required>\r\n");
      out.write("          <label class=\"form-check-label\">Female</label>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <span class=\"input-group-text\"><i class=\"fas fa-birthday-cake\"></i></span>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"age\" placeholder=\"Enter your age\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"input-group\">\r\n");
      out.write("        <span class=\"input-group-text\"><i class=\"fas fa-calendar\"></i></span>\r\n");
      out.write("        <input type=\"date\" class=\"form-control\" name=\"dob\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary w-100 mt-3\">Submit</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
